spring:
  application:
    name: be-interview-prep
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/be_interview_prep}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  data:
    web:
      pageable:
        max-page-size: 100
  flyway:
    locations: classpath:db/migration
