CREATE TABLE task (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(100)             NOT NULL,
    description VARCHAR(1000),
    status      VARCHAR(20)              NOT NULL,
    due_date    DATE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_task_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'DONE'))
);

CREATE INDEX idx_task_status ON task (status);
