CREATE TABLE short_url (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(8)               NOT NULL,
    original_url VARCHAR(2048)            NOT NULL,
    visit_count  BIGINT                   NOT NULL DEFAULT 0,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_short_url_code UNIQUE (code)
);
