CREATE TABLE product (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200)             NOT NULL,
    category   VARCHAR(30)              NOT NULL,
    price      NUMERIC(10, 2)           NOT NULL,
    stock      INTEGER                  NOT NULL,
    rating     NUMERIC(2, 1)            NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_product_category CHECK (category IN
        ('ELECTRONICS', 'BOOKS', 'CLOTHING', 'HOME', 'SPORTS', 'TOYS', 'GROCERY', 'BEAUTY')),
    CONSTRAINT chk_product_price CHECK (price >= 0),
    CONSTRAINT chk_product_stock CHECK (stock >= 0),
    CONSTRAINT chk_product_rating CHECK (rating BETWEEN 0 AND 5)
);

CREATE INDEX idx_product_category_price ON product (category, price);
CREATE INDEX idx_product_price ON product (price);
CREATE INDEX idx_product_created_at ON product (created_at);
CREATE INDEX idx_product_rating ON product (rating);
CREATE INDEX idx_product_name ON product (name);
