CREATE TABLE customer_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     BIGINT                   NOT NULL,
    idempotency_key VARCHAR(100)             NOT NULL,
    request_hash    VARCHAR(64)              NOT NULL,
    status          VARCHAR(20)              NOT NULL,
    total           NUMERIC(14, 2)           NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    cancelled_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_customer_order_customer FOREIGN KEY (customer_id) REFERENCES app_user (id),
    CONSTRAINT uk_customer_order_idempotency UNIQUE (customer_id, idempotency_key),
    CONSTRAINT chk_customer_order_status CHECK (status IN ('PLACED', 'CANCELLED')),
    CONSTRAINT chk_customer_order_total CHECK (total >= 0)
);

CREATE INDEX idx_customer_order_customer_created ON customer_order (customer_id, created_at);

CREATE TABLE order_item (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT         NOT NULL,
    product_id BIGINT         NOT NULL,
    quantity   INTEGER        NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES customer_order (id) ON DELETE CASCADE,
    CONSTRAINT uk_order_item_order_product UNIQUE (order_id, product_id),
    CONSTRAINT chk_order_item_quantity CHECK (quantity > 0),
    CONSTRAINT chk_order_item_unit_price CHECK (unit_price >= 0)
);
